### ISSUE TITLE
Call Activity - list of processes is not displaying the correct titles

### ISSUE THREAD

**Issue by danloa** [ProcessMaker/spark-modeler#305]
When configuring a subprocess (callActivity) the list of processes is not showing the correct texts. In this example I have two pools (named admin and create process) but When configuring the call activity instead of those titles, the default text (in this case Process_1 and Process_2) is displayed.

![image](https://user-images.githubusercontent.com/14875032/55104524-e21c3680-50a0-11e9-90c1-4ca07d62f0ea.png)

**Comment by chipit24** [comment]
@danloa This is because a pool is a visual representation of a participant (in a collaboration), and changing the name of a pool changes only the name attribute for the _participant_ element, **not** the _process_ it references.

There are a couple initial ways I can solve this:
* Add another text field to the config to allow changing the name of the process (this is how Camunda does it).
* Have the name property refer to the process name, and display that instead of the actual participant name.

**Comment by caleeli** [comment]
@chipit24 @danloa @velkymx  Camunda has an interesting way to select a process within a pool using a second click on the pool, this way the user could change between the pool and the participant and set the process name and id.

**Comment by chipit24** [comment]
Got a draft PR up to address this issue (as per discussion with @velkymx): https://github.com/ProcessMaker/modeler/pull/308. The list of processes will be from the API's `/processes` endpoint.

When testing, the generated XML for a _Call Activity_ seems valid, but results in an error, `The bpm definition is not valid`, when trying to save in BPM. @caleeli would you know why this happens?

**Comment by chipit24** [comment]
The error when trying to save a process which contains a _Call Activity_:

```
PUT https://bpm4.local.processmaker.com/api/1.0/processes/1 422

errors: {
  bpmn: [
    "DOMDocument::schemaValidate(): Element '{http://www.omg.org/spec/BPMN/20100524/MODEL}callActivity', attribute 'calledElement': '4' is not a valid value of the atomic type 'xs:QName'."
  ],
  message: "The bpm definition is not valid"
}
```

In the above case, `4` for the value of `calledElement` is the ID of the selected process. I'm not sure what the `xs:QName` property is that I should use instead.
