### ISSUE TITLE
Mini Map

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/spark-modeler#329]
Need to know how much effort to show a mini process map that is clickable to that location on the canvas.

<img width="705" alt="Screenshot 2019-04-11 08 11 08" src="https://user-images.githubusercontent.com/535300/55968708-650cc780-5c31-11e9-8c52-3e2809a92a75.png">

**Comment by chipit24** [comment]
There's an example of a mini-map on the JointJS website: https://resources.jointjs.com/tutorial/multiple-papers. It seems setting up a basic mini-map won't take too long; making it interactive and having it show the viewport overlay would be the tricky part. I'd give it 2-3 days to implement.

**Comment by velkymx** [comment]
Let's hold on this.

**Comment by tuantruong625** [comment]
@velkymx 
The mini-map is implemented. We thought the best place for it would be the top left corner of the canvas because if it were to be placed in the bottom right corner the validation drawer would overlap the mini-map. 

Also we styled the buttons with the bootstrap classes.

<img width="1677" alt="Screen Shot 2019-04-25 at 4 00 10 PM" src="https://user-images.githubusercontent.com/26545455/56764656-3f280c80-6773-11e9-848f-a452df5ee19c.png">
 
How do we want to handle interaction with the mini-map ?

**Ideas**
- scale the mini-map with the main canvas 
- clicking an area on the mini-map will move the canvas to where you clicked
- dragging either mini-map or canvas will mirror each other
