### ISSUE TITLE
SequenceFlow between Gateway and CallActivity

### ISSUE THREAD

**Issue by caleeli** [ProcessMaker/spark-modeler#334]
Currently if the sequence flow outcomes a Gateway and incomes a CallActivity does not have the Start Event property.

![image](https://user-images.githubusercontent.com/8028650/55983994-6c9c9280-5c6a-11e9-99fb-7e43ce3fbd96.png)

**Comment by chipit24** [comment]
@caleeli This will be fixed as part of https://github.com/ProcessMaker/spark-modeler/issues/328. I think the real question we should solve in this issue is how to handle both labels.

In the situation depicted above, should both the start event name and the gateway expression appear above the sequence flow? Or only the start event name? Or only the expression?

@velkymx What do you think?

**Comment by caleeli** [comment]
@chipit24 Both, because they are required, StartEvent is required for the CallActivity, and Expression for the Exclusive Gateway.

**Comment by velkymx** [comment]
@chipit24 For the start name + call activity - Only the expression, like another conditional seq flow

**Comment by chipit24** [comment]
Ok, I've updated https://github.com/ProcessMaker/spark-modeler/pull/337 to prefer showing the expression over event name when both are available:

![spark-flow-expression](https://user-images.githubusercontent.com/7561061/56055358-4ee13300-5d27-11e9-972c-36c710b03a5d.gif)
