### ISSUE TITLE
Element Flows Delete Vertices 

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/spark-modeler#363]
When I draw a crazy line, I want to be able to delete vertices that are created that are wild. Current implementation, while much better, still produces lots of weird loops and out of control lines.

**Comment by tuantruong625** [comment]
@velkymx I believe this issue was addressed in https://github.com/ProcessMaker/spark-modeler/pull/405. While not obvious to the user you can delete a vertices by double clicking the dot on the vertices. I think a tooltip or a helper text when highlighting the sequence flow would make for a better user experience.

<img width="1665" alt="Screen Shot 2019-06-03 at 1 23 48 PM" src="https://user-images.githubusercontent.com/26545455/58821456-195c1600-8603-11e9-8910-cdfd6f89b00c.png">

**Fix of the weird loops in spark**
https://drive.google.com/open?id=1xDwMNcsoMoBplt3Wh-uNYQXsr1JyP5EC

**Comment by velkymx** [comment]
OK closing with note: Double click to remove vertices
